### ISSUE TITLE
Hook for option selected via Enter

### ISSUE THREAD

**Issue by ntharim** [ezequiel/react-typeahead-component#1]
There's `onOptionClick` for when an option is clicked but how do you detect option selection when the user presses Enter after moving up and down with arrow keys?

**Comment by ezequiel** [comment]
Good question. This is a good use case I may have missed. For our use cases, we [set the input value when arrowing](https://github.com/ezequiel/react-typeahead-component/blob/master/example/youtube/js/app.jsx#L43-45), and the input value was enough information to perform some action. I can see use cases where the input value isn't necessarily enough, and the actual selected option data is needed.

I can pass the option data, and `selectedIndex` as two extra parameters when `onKeyDown` is fired (like `onOptionClick`). What do you think?

**Comment by ntharim** [comment]
Yeah that would work. Another option is to have `onOptionSelected` that can detect both clicks and Enter keydowns. Either is fine for me so up to you what you want to implement :D.

**Comment by ezequiel** [comment]
@nthtran I've added this new functionality as part of release `0.3.0`. I decided to go with the `onKeyDown` approach, as it will probably offer greater flexibility when strange requirements come into play.

**Comment by ntharim** [comment]
Absolutely. Keep up the good work! :+1:
