### ISSUE TITLE
Better focus management

### ISSUE THREAD

**Issue by ghost** [ezequiel/react-typeahead-component#18]
First off, thanks for this component. It's pretty awesome. Though I'm having some problems with focus management. The problem is that, following a selection from the drop-down menu, or pressing `Enter` from the input, the focus disappears form the `input` element rather than return to it. And though it's possible to use `e.currentTarget.focus()` from `onKeyDown`, for example, it's not possible to do so from `onOptionClick`. Rather than handling this behavior in callbacks it'd be nice to see it as a default behavior. Thoughts?

**Comment by ezequiel** [comment]
Right, [we blur the input on `Enter`](https://github.com/ezequiel/react-typeahead-component/blob/master/src/components/typeahead.jsx#L411). I'm open to removing it.  As for `onOptionClick`-- I'd have to focus the `<input>` manually. I suppose we can do this too. Can you send a pull request my way?

**Comment by ghost** [comment]
@ezequiel subbed a pr. please lmk what you think
