### ISSUE TITLE
use ReactDOM.findDOMNode

### ISSUE THREAD

**Issue by arahansen** [ezequiel/react-typeahead-component#34]
https://github.com/ezequiel/react-typeahead-component/blob/master/src/components/typeahead.jsx#L505

Is causing a warning on react@0.14.7 

![image](https://cloud.githubusercontent.com/assets/8746094/14025904/803d0f84-f1ad-11e5-8341-0f183c5b6645.png)

**Comment by hackingbeauty** [comment]
+1 Can we get this fixed?

**Comment by mjshepherd** [comment]
+1

**Comment by mrhieund** [comment]
+1

**Comment by anishmprasad** [comment]
`ReactDOM.findDOMNode()` use this instead of `getDOMNode(...)` 

if issue in focus function in typeahead.jsx use `ReactDOM.findDOMNode(this.refs.input)` instead of `this.refs.input.getDOMNode()`
